### ISSUE TITLE
Migrate to V2 embedding

### ISSUE THREAD

**Issue by deepak786** [SunnyApp/flutter_contact#68]
migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by tkeithblack** [comment]
+1 I'm receiving the following warning with Flutter 2.5.0 using flutter_contact version: 0.9.1+7:

"The plugin `flutter_contact` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration."

**Comment by wish32** [comment]
+1 Good plugin! 
I'm facing the same problem...

**Comment by deepak786** [comment]
@tkeithblack @wish32 

I have submitted the PR (https://github.com/SunnyApp/flutter_contact/pull/69) which not only migrates to Android V2 embedding but also adds new features with some adjustments in the Plugin.
Until the PR is not merged, you can use it in your projects.

Add or update the following in your `pubspec.yml` file.

```
dependency_overrides:
  flutter_contact:
    git:
      url: https://github.com/deepak786/flutter_contact
      ref: agendaboa_patch
```

Use it and share the feedback accordingly.

If you like the work, Don't hesitate to buy me coffee.
<a href="https://www.buymeacoffee.com/deepakdroid" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" width="150px"></a>

**Comment by rabi-palmtree** [comment]
+1
Hope this will be resolved soon

**Comment by wangbo4020** [comment]
```log
Running "flutter pub get" in Xxx...                   5.9s

The plugin `flutter_contact` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

Process finished with exit code 0
```
</font>

**Comment by vernalclareai** [comment]
Hi, any update to fix the warning?
Thanks.

**Comment by deepak786** [comment]
@vernalclareai 
you can use this patch

```
dependency_overrides:
  flutter_contact:
    git:
      url: https://github.com/deepak786/flutter_contact
      ref: agendaboa_patch
```

It also resolved the above issue.
